export class sessionStorageItems {
    public static SS_TOKEN: string = "token"
    public static SS_USUARIO: string = "Usuario"
    public static SS_DEPARTAMENTO: string = "Departamento"
    public static SS_MUNICIPALIDAD: string = "Municipalidad"
    public static SS_ID_MUNICIPALIDAD: string = "IdMunicipalidad"
    public static SS_ID_PERFIL: string = "Id_Perfil"
    public static SS_NOMBRE_PERFIL: string = "Nombre_Perfil"
    public static SS_NOMBRE_USUARIO: string = "Nombre_Usuario"
    public static SS_COD_DEPA: string = "Coddepa"
    public static SS_ID_ZONA: string = "IdZona"
    public static SS_ID_USUARIO: string = "IdUsuario"
    public static SS_TIPO: string = "Tipo"
    public static SS_ID_SEGUIMIENTO_MONITOREO_OBRA: string = "idSeguimiento"
    public static SS_ID_SEGUIMIENTO_MONITOREO_OBRA_REGISTRO: string = "idSeguimiento_registro"
}
